(define (make-monitored f)
    (let ((call-count 0))
        (define (inc-count input)
            (begin (set! call-count (+ call-count 1))
                    (f input)))
        (define (dispatch m)
            (if (eq? m `how-many-calls?)
                call-count
                (inc-count m)))
        dispatch))

(define (make-account balance password alert-count)
    (let ((account-pw password)
          (incorrect-pw-count 0))
        (define (withdraw amount)
            (if (>= balance amount)
                (begin (set! balance (- balance amount))
                       balance)
                "Insufficient funds"))
        (define (deposit amount)
            (set! balance (+ balance amount)))
        (define (dispatch pw m)
            (if (eq? pw account-pw)
                (begin (set! incorrect-pw-count 0)
                    (cond ((eq? m `withdraw) withdraw)
                          ((eq? m `deposit) deposit)
                          (else (error "Unknown request -- MAKE-ACCOUNT" m))))
                (begin (set! incorrect-pw-count (+ incorrect-pw-count 1))
                       (if (> incorrect-pw-count alert-count)
                           (lambda (m) (call-the-cops))
                           (lambda (pw) "Incorrect password")))))
        dispatch))

(define (call-the-cops)
    "911!")


; should call the cops
(define acc (make-account 100 `secret-password 7))
((acc `secret-password `withdraw) 40)
((acc `some-other-password `deposit) 50)
((acc `some-other-password `deposit) 50)
((acc `some-other-password `deposit) 50)
((acc `some-other-password `deposit) 50)
((acc `some-other-password `deposit) 50)
((acc `some-other-password `deposit) 50)
((acc `some-other-password `deposit) 50)
((acc `some-other-password `deposit) 50)

; should reset and be fine
(define acc (make-account 100 `secret-password 7))
((acc `secret-password `withdraw) 40)
((acc `some-other-password `deposit) 50)
((acc `some-other-password `deposit) 50)
((acc `some-other-password `deposit) 50)
((acc `some-other-password `deposit) 50)
((acc `secret-password `withdraw) 40)
((acc `some-other-password `deposit) 50)
((acc `some-other-password `deposit) 50)
((acc `some-other-password `deposit) 50)
((acc `some-other-password `deposit) 50)
