(define (make-account balance password)
    (let ((account-pw password))
        (define (withdraw amount)
            (if (>= balance amount)
                (begin (set! balance (- balance amount))
                       balance)
                "Insufficient funds"))
        (define (deposit amount)
            (set! balance (+ balance amount)))
        (define (dispatch pw m)
            (if (eq? pw account-pw)
                (cond ((eq? m `withdraw) withdraw)
                      ((eq? m `deposit) deposit)
                      (else (error "Unknown request -- MAKE-ACCOUNT" m)))
                (error "Incorrect password")))
        dispatch))

(define acc (make-account 100 `secret-password))
((acc `secret-password `withdraw) 40)
((acc `some-other-password `deposit) 50)