; Two procedures for adding two positive integers
(define (+ a b)
	(if(= a 0)
		b
		(inc (+ (dec a) b))))

(define (+ a b)
	(if(= a 0)
		b
		(+ (dec a) (inc b))))


; Using the substitution model, illustrate the process generated by each
; procedure in evaluating (+ 4 5).  Are these processes iterative or recursive?

; Top procedure
;	(+ 4 5)
;	(inc (+ 3 5))
;   (inc (inc (+ 2 5)))
;   (inc (inc inc(+ 1 5))))
;   (inc (inc (inc (inc (+ 0 5)))))
;   (inc (inc (inc (inc 5))))
;   (inc (inc (inc 6)))
;   ....
;   9
;
; This first procedure is a recursive process.  The process grows and shrinks, and 
; hidden information is contained (namely, the chained operations, i.e. calls to inc).
;
; Bottom procedure
;	(+ 4 5)
;   (+ 3 6)
;   (+ 2 7)
;	(+ 1 8)
;	(+ 0 9)
;	9
;
; The bottom procedure is an iterative process (doesn't 'grow and shrink').
